### ISSUE TITLE
Testing KaHyPar mistakes

### ISSUE THREAD

**Issue by ChengweiLou** [kahypar/KaHyPar.jl#10] opened 2021-02-19 14:51 UTC
julia> Pkg.test("KaHyPar")
    Testing KaHyPar
Status `C:\Users\2544035L\AppData\Local\Temp\jl_b45JpT\Manifest.toml`
  [b99e7846] BinaryProvider v0.5.10
  [2a6221f6] KaHyPar v0.1.0 #master (https://github.com/kahypar/KaHyPar.jl.git)
  [2a0f44e3] Base64
  [8ba89e20] Distributed
  [b77e0a4c] InteractiveUtils
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [9a3f8284] Random
  [ea8e919c] SHA
  [9e88b42a] Serialization
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [8dfed614] Test
ERROR: LoadError: C:\Users\2544035L\.julia\packages\KaHyPar\52iYf\src\..\deps\deps.jl does not exist, Please re-run Pkg.build("KaHyPar"), and restart Julia.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\2544035L\.julia\packages\KaHyPar\52iYf\src\KaHyPar.jl:13
 [3] include(::Module, ::String) at .\Base.jl:377
 [4] top-level scope at none:2
 [5] eval at .\boot.jl:331 [inlined]
 [6] eval(::Expr) at .\client.jl:449
 [7] top-level scope at .\none:3
in expression starting at C:\Users\2544035L\.julia\packages\KaHyPar\52iYf\src\KaHyPar.jl:9
ERROR: LoadError: Failed to precompile KaHyPar [2a6221f6-aa48-11e9-3542-2d9e0ef01880] to C:\Users\2544035L\.julia\compiled\v1.4\KaHyPar\CqBtU_5cVsk.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
 [6] include(::String) at .\client.jl:439
 [7] top-level scope at none:6
in expression starting at C:\Users\2544035L\.julia\packages\KaHyPar\52iYf\test\runtests.jl:2
ERROR: Package KaHyPar errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Types.jl:53
 [2] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:1510
 [3] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:316
 [4] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:303
 [5] #test#68 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:297 [inlined]
 [6] test at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:297 [inlined]
 [7] #test#67 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:296 [inlined]
 [8] test at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:296 [inlined]
 [9] test(::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:295
 [10] test(::String) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\API.jl:295
 [11] top-level scope at none:0

**Comment by SebastianSchlag** [comment] 2021-02-22 19:57
@jalving Do you have any ideas on this?

**Comment by jalving** [comment] 2021-02-25 17:25
@SebastianSchlag I think this is a duplicate of #9. Since KaHyPar doesn't install on windows, trying to use the interface without the library will fail.  I am going to close this one and comment on the other issue.

**Closed by jalving** 2021-02-25 17:25 UTC
